### PR TITLE
Address bug in check-whois-domain-expiration-multi.rb causing it to crash

### LINKED ISSUE #67: check-whois-domain-expiration-multi.rb v2.1.1 fails with "undefined local variable or method `domain_result'"
Running on version 2.1.1 I get the following error:

```
Check failed to run: undefined local variable or method `domain_result' for #, ["/nix/store/x8fgw5n17bna0khbwdh8qxpa7y0v2gd9-sensu-1.2.0/lib/ruby/gems/2.3.0/gems/sensu-plugins-network-checks-2.1.1/bin/check-whois-domain-expiration-multi.rb:97:in `block in expiration_results'", "/nix/store/x8fgw5n17bna0khbwdh8qxpa7y0v2gd9-sensu-1.2.0/lib/ruby/gems/2.3.0/gems/sensu-plugins-network-checks-2.1.1/bin/check-whois-domain-expiration-multi.rb:86:in `each'", "/nix/store/x8fgw5n17bna0khbwdh8qxpa7y0v2gd9-sensu-1.2.0/lib/ruby/gems/2.3.0/gems/sensu-plugins-network-checks-2.1.1/bin/check-whois-domain-expiration-multi.rb:86:in `expiration_results'", "/nix/store/x8fgw5n17bna0khbwdh8qxpa7y0v2gd9-sensu-1.2.0/lib/ruby/gems/2.3.0/gems/sensu-plugins-network-checks-2.1.1/bin/check-whois-domain-expiration-multi.rb:113:in `run'", "/nix/store/x8fgw5n17bna0khbwdh8qxpa7y0v2gd9-sensu-1.2.0/lib/ruby/gems/2.3.0/gems/sensu-plugin-1.4.5/lib/sensu-plugin/cli.rb:58:in `block in '"]
```

Rolling back to 2.1.0 makes things work again.

### PR DESCRIPTION
**Pull request by majormoses**
fix issue with accessing a variable that can't exist yet, return the raw results.

Signed-off-by: Ben Abrams <me@benabrams.it>

## Pull Request Checklist

fixes #67 

caused by #65 

#### General

- [ ] Update Changelog following the conventions laid out on [Keep A Changelog](http://keepachangelog.com/)

- [ ] Update README with any necessary configuration snippets

- [ ] Binstubs are created if needed

- [ ] RuboCop passes

- [ ] Existing tests pass

#### Purpose
Fix an issue where `expires_on` is nil and breaks rather than returning the proper critical result.

#### Known Compatibility Issues
None

### CODE REVIEW

**Comment by majormoses** [comment]
closing in favor of #71
